### ISSUE TITLE
Can't build Tyk locally

### ISSUE THREAD

**Issue by richard-hulm** [TykTechnologies/tyk#276]
Trying to build Tyk (develop branch) on a machine running Fedora 21 (Go v1.6.2)

Getting errors - firstly ones due to a nonexistent dependency (fixed in #275 ?)

After that - doing a go get I get the following errors

```
# github.com/TykTechnologies/tyk
./middleware_jwt.go:126: invalid type assertion: token.Claims.(jwt.MapClaims) (non-interface type map[string]interface {} on left)
./middleware_jwt.go:127: invalid type assertion: token.Claims.(jwt.MapClaims) (non-interface type map[string]interface {} on left)
./middleware_jwt.go:181: invalid type assertion: token.Claims.(jwt.MapClaims) (non-interface type map[string]interface {} on left)
./middleware_jwt.go:190: invalid type assertion: token.Claims.(jwt.MapClaims) (non-interface type map[string]interface {} on left)
./middleware_jwt.go:220: invalid type assertion: token.Claims.(jwt.MapClaims) (non-interface type map[string]interface {} on left)
./middleware_jwt.go:224: invalid type assertion: token.Claims.(jwt.MapClaims) (non-interface type map[string]interface {} on left)
./middleware_openid.go:101: invalid type assertion: token.Claims.(jwt.MapClaims) (non-interface type map[string]interface {} on left)
./middleware_openid.go:102: invalid type assertion: token.Claims.(jwt.MapClaims) (non-interface type map[string]interface {} on left)
./middleware_openid.go:123: use of .(type) outside type switch
```

Any ideas?

**Comment by lonelycode** [comment]
Have you pulled the latest master (2.2)? Upstream dependencies in the JWT library and OIDC libraries caused this failure. We've fixed them and forked OIDC to prevent it, but if your version is before we applied these fixes it will break.

We build dev nightly with clean dependencies and dev was very recently merged to master for the 2.2 release, so it *should* all be ok.

**Comment by richard-hulm** [comment]
Yes - I'm on the latest version of the develop branch. (well, technically I'm on the commit from the PR I just submitted)

The JWT being imported in middleware_jwt is 	"github.com/dgrijalva/jwt-go" - doesn't look like the forked version?

**Comment by lonelycode** [comment]
Hmmm, I wonder there is *another* breaking change that's been introduced...

**Comment by richard-hulm** [comment]
Urgh - sorry.

Went into my local copy of both of the repos causing a problem and did a git pull and it builds now.

Still getting used to golang - I imagined goget would get the latest version of all the dependencies but apparantly not (??)

**Comment by richard-hulm** [comment]
(So just for posterity - I was using the latest version of Tyk, but had to do

cd GO_HOME/src/github.com/openid2go/openid
git pull
cd GO_HOME/src/github.com/dgrijalva/jwt-go/
git pull

**Comment by lonelycode** [comment]
Nah, that would be too easy! `go get -u` will update deps :-) 

That's why we do the nightlies, they are always clan builds in an empty baseline - they flag up when a dependency changes!
